### ISSUE TITLE
Product capabilities 

### ISSUE THREAD

**Issue by JitBox** [zeronetworks/cornershot#15]
This is an awesome tool, and I am excited to get to using it. I had a couple questions on capabilities with using Cornershot along with Shothound. 

1. Is there a way to exclude IPs or Computer names? I have a sensitive network I am working with and id like to exclude some specific IPs from scanning. If I understood correctly, I could use Shothound to look into my neo4j/Bloodhound and gather all shortest path to DAs. itll use those paths to query with Cornershot and return routable paths. Im sure in some of those short paths there are some IPs I want excluded. Is there a way to accomplish this? 

2. Do we know when this will be data we can return into Bloodhound for visualization?

**Comment by sagiesec** [comment]
Thank you @JitBox for using CornerShot / ShotHound.

Regarding #1: This is not supported OOTB. You can update the script with your limitations in the validate_paths(self) function. Just before the add_shot() call, you can filter out destinations and targets that you don't wish to query.

Regarding #2: I would recommend checking out BlueHound: https://github.com/zeronetworks/BlueHound. 
You can visualize any type of neo4j data. 

We also have a slack channel to discuss OSS we develop with the community - you can send a request to join to support@zeronetworks.com.
