### ISSUE TITLE
Understanding how carrier hosts work

### ISSUE THREAD

**Issue by AinoL** [zeronetworks/cornershot#18]
Hello!

How do I install the agents to deploy cornershot? From the readme.md: "CornerShot can simplify this process by using one (or very few) agents that can query other hosts in the network, to determine their access to remote hosts."

What does an agent mean in this case?

Thank you for your answer

**Comment by sagiesec** [comment]
I meant to install cornershot (I've called each installation agent). 
So the normal "pip install cornershot"
